{% set name = "tardigrade_vector_tools" %}
{% set version = "0.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  path: '..'

build:
  number: 0
  script_env:
    - SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}
  script:
    - set -x
    # Build and install c++ libraries
    - cmake -S . -B build -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_LIBDIR=lib
    - cmake --install build --prefix ${PREFIX}
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
    - make
    - cmake >=3.30
    - tardigrade_error_tools >=0.7
  host:
    - breathe >=4.3.0
    - sphinx >=3.0.4
    - sphinx_rtd_theme >=0.4.3
    - sphinxcontrib-bibtex
    - setuptools >=77
    - setuptools_scm >=8
    - eigen >=3.3.7
    - libboost-python-devel >=1.82
    - doxygen
  run:
    - tardigrade_error_tools >=0.7

test:
  requires:
    - {{ compiler('cxx') }}
    - make
    - cmake >=3.30
    - libboost-python-devel >=1.82
    - doxygen
    - sphinx >=3.0.4
  source_files:
    - CMakeLists.txt
    - src/cpp/tests/CMakeLists.txt
    - src/cpp/tests/test_tardigrade_vector_tools.cpp
    - src/cpp/tests/test_tardigrade_interp_ndCartesian.cpp
  commands:
    - set -x
    - cmake -S . -B build -DCMAKE_BUILD_TYPE=conda-test -DCMAKE_INSTALL_LIBDIR=lib
    - cmake --build build --verbose --parallel 4
    - ctest --test-dir build --output-on-failure -R 'test_' --parallel 4

about:
  home: https://github.com/UCBoulder/tardigrade_vector_tools
  license: BSD-3-Clause
  license_file: LICENSE
  summary: 'A collection of tools for vector manipulation'
  description: |
    tardigrade-vector-tools A collection of tools for C++ that make interfacing with vectors easier
    and less prone to error. These tools also allow the user access to the powerful Eigen library which provides matrix
    utilities in such a way that Eigen does not need to be used explicitly in the user's code.
  dev_url: https://github.com/UCBoulder/tardigrade_vector_tools
