name: environment
channels:
  - defaults
dependencies:
  - python>=3.7
  - sphinx>=3.0.4
  - sphinx_rtd_theme>=0.4.3
  - cython
  - pytest
  - numpy
  - pip
  - pip:
    - --requirement requirements.txt
